---
engine: julia
---

# cl_sop {#sec-doc}
    

::: {.callout-note appearance="simple" title="docblock" collapse=false}    


```{julia}
#| eval: false
cl_sop(

```

sop*dgp::ICSTS, lam, L0, cl*init, d1::Int, d2::Int, reps=10*000;   chart*choice=3, jmin=4, jmax=6, verbose=false )
 
Compute the control limit for a given in-control process. The input parameters are:
 
  * `sop_dgp`: The in-control spatial process (ICSTS) to use for the control limit.
  * `lam::Float64`:  A scalar value for lambda for the EWMA chart.
  * `L0::Float64`: The desired average run length.
  * `cl_init::Float64`: The initial value for the control limit.
  * `d1::Int`: The first (row) delay for the spatial process.
  * `d2::Int`: The second (column) delay for the spatial process.
  * `reps::Int`: The number of replications to compute the ARL.
  * `chart_choice::Int`: The chart choice for the SOP chart.
  * `jmin`: The minimum number of values to change after the decimal point in the control limit.
  * `jmax`: The maximum number of values to change after the decimal point in the control limit.
  * `verbose::Bool`: A boolean to indicate whether to print the control limit and ARL for each iteration.


:::
    

