project:
  type: website
  output-dir: site
execute:
  freeze: false
  cache: false
  warning: false
website:
  # title: "OrdinalPatterns.jl"
  page-navigation: true
  bread-crumbs: true


  search:
    show-item-context: true
    type: overlay

  navbar:
    background: primary

    left:
      - text: "OrdinalPatterns.jl"
        href: index.qmd      
      - text: "Installation"
        href: page_files/installation.qmd  
      - text: "Introduction"
        href: page_files/introduction.qmd  
      - text: "OPs"
        href: page_files/op.qmd
      - text: "SOPs"
        href: page_files/sop.qmd
      - text: "GOPs"
        href: page_files/gop_tutorials.qmd
      - text: "API"
        href: page_files/api_reference.qmd

    tools:
    - icon: github
      href: https://github.com/AdaemmerP/OrdinalPatterns.jl
      text: "OrdinalPatterns.jl"

  sidebar:
    - title: "API"    
      style: "docked"
      background: light
      #collapse-level: 1
      contents:
        - page_files/api_reference.qmd
        - section: "Types for ordinal patterns"
          contents:
        - section: "Types for generalized ordinal patterns"
          contents:  
        - section: "Types for spatial data"
          contents:
            - reference/SAR1.qmd
            - reference/SAR11.qmd
            - reference/SQINMA11.qmd
            - reference/SQMA11.qmd
        - section: "Functions for spatial data"
          contents:
            - reference/arl_sop.qmd
            - reference/arl_sacf.qmd
    - title: "SOPs"
      style: "docked"
      background: light
      #collapse-level: 1
      contents:
        - page_files/sop.qmd
        - section: "SOP Applications"
          contents:
            - page_files/sop_tutorial.qmd
            - page_files/sop_replication.qmd   
    - title: "OPs"
      style: "docked"
      background: light
      #collapse-level: 1
      contents:
        - page_files/op.qmd
        - section: "OP Applications"
          contents:
            - page_files/op_tutorial.qmd
            - page_files/op_replication.qmd                 

  page-footer: "Website generated with [Quarto](https://quarto.org/) and [QuartoDocBuilder.jl](https://github.com/vituri/QuartoDocBuilder.jl)"


engine: julia

format:
  html:
    theme: flatly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    preview-links: true
    toc: true
    toc-depth: 3
    toc-expand: true 
